### ISSUE TITLE
What alignment/cropping/format?

### ISSUE THREAD

**Issue by ghost** [LeslieZhoa/HeadSwap#1]
Hello,

I tried your repo, but the results didn't work. What preprocessing do I need to do on the images before running them through inference.py?

Thanks!

**Comment by LeslieZhoa** [comment]
Hi @antonsanchez, this project do not need extend preprocessing. I put some test images here and you can get the result by running inference.py only. 
If you can not run anyway, could you show the errors here?
Hope you get a good result!

**Comment by ghost** [comment]
I figured it out. Your face detection doesn't work when the face is already cropped.

**Comment by LeslieZhoa** [comment]
Hi @antonsanchez , there is a [crop_align param](https://github.com/LeslieZhoa/HeadSwap/blob/main/inference.py#L180) and you can change in your way
