### ISSUE TITLE
If you get errors in Colab

### ISSUE THREAD

**Issue by gibiee** [LeslieZhoa/HeadSwap#10]
Try this version :
https://colab.research.google.com/drive/1zoRLaQvpqEBLpxk-Vp4MtNnkaku5Lb5t?usp=sharing

I think the `face-alignment` version seems to be particularly prone to errors.

**Comment by kampelmuehler** [comment]
In fact `face-alignment==1.3.5` is the latest working version.

**Comment by kampelmuehler** [comment]
I'll take it back. Best to stay with `face-alignment==1.3.3` as you do in your version @gibiee

**Comment by gibiee** [comment]
@kampelmuehler Thanks for your efforts!

**Comment by Part-Work** [comment]
I run this version, but I got this error in last section.
```
oup = model.run_single(source_path, target_path, crop_align=True,cat=True)
```
 please help me


```
ValueError                                Traceback (most recent call last)
[<ipython-input-16-9f1905b26271>](https://localhost:8080/#) in <cell line: 1>()
----> 1 oup = model.run_single(source_path, target_path, crop_align=True,cat=True)
      2 cv2_imshow(oup)

3 frames
[/content/HeadSwap/model/third/Deep3dRec/preprocess.py](https://localhost:8080/#) in align_img(img, lm, lm3D, mask, target_size, rescale_factor)
     75     # processing the image
     76     img_new, lm_new, mask_new = resize_n_crop_img(img, lm, t, s, target_size=target_size, mask=mask)
---> 77     trans_params = np.array([w0, h0, s, t[0], t[1]],dtype=np.float32)
     78 
     79     return trans_params, img_new, lm_new, mask_new

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
```

> Try this version : https://colab.research.google.com/drive/1zoRLaQvpqEBLpxk-Vp4MtNnkaku5Lb5t?usp=sharing
> 
> I think the `face-alignment` version seems to be particularly prone to errors.

**Comment by LeslieZhoa** [comment]
Thanks your reply. You can also change [here](https://github.com/LeslieZhoa/HeadSwap/blob/main/process/process_func.py#L19) to face_alignment.LandmarksType.THREE_D

**Comment by mnotgod96** [comment]
> I run this version, but I got this error in last section.
> 
> ```
> oup = model.run_single(source_path, target_path, crop_align=True,cat=True)
> ```
> 
> please help me
> 
> ```
> ValueError                                Traceback (most recent call last)
> [<ipython-input-16-9f1905b26271>](https://localhost:8080/#) in <cell line: 1>()
> ----> 1 oup = model.run_single(source_path, target_path, crop_align=True,cat=True)
>       2 cv2_imshow(oup)
> 
> 3 frames
> [/content/HeadSwap/model/third/Deep3dRec/preprocess.py](https://localhost:8080/#) in align_img(img, lm, lm3D, mask, target_size, rescale_factor)
>      75     # processing the image
>      76     img_new, lm_new, mask_new = resize_n_crop_img(img, lm, t, s, target_size=target_size, mask=mask)
> ---> 77     trans_params = np.array([w0, h0, s, t[0], t[1]],dtype=np.float32)
>      78 
>      79     return trans_params, img_new, lm_new, mask_new
> 
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
> ```
> 
> > Try this version : https://colab.research.google.com/drive/1zoRLaQvpqEBLpxk-Vp4MtNnkaku5Lb5t?usp=sharing
> > I think the `face-alignment` version seems to be particularly prone to errors.

change the line 77 to
`trans_params = np.array([w0, h0, s, t[0][0], t[1][0]],dtype=np.float32)`

**Comment by GoldenFlash0824** [comment]
I tried on colab, but there is an error like:
![Uploading Capture.JPG…]()

**Comment by GoldenFlash0824** [comment]
I tried on colab, but there is an error like:
![Capture](https://github.com/user-attachments/assets/bfdd6e1a-8715-4ecf-b9d2-4dfb2d6544dd)

**Comment by GoldenFlash0824** [comment]
----> 1 model = Infer(
      2             #'checkpoint/Aligner/058-00008100.pth',
      3             'pretrained_models/epoch_00190_iteration_000400000_checkpoint.pt',
      4             'pretrained_models/Blender-401-00012900.pth',
      5             'pretrained_models/parsing.pth',
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-17-a964d5178ee6>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model = Infer(
      2             #'checkpoint/Aligner/058-00008100.pth',
      3             'pretrained_models/epoch_00190_iteration_000400000_checkpoint.pt',
      4             'pretrained_models/Blender-401-00012900.pth',
      5             'pretrained_models/parsing.pth',

2 frames
[/usr/lib/python3.10/enum.py](https://localhost:8080/#) in __getattr__(cls, name)
    435             return cls._member_map_[name]
    436         except KeyError:
--> 437             raise AttributeError(name) from None
    438 
    439     def __getitem__(cls, name):

AttributeError: _3D
