### ISSUE TITLE
Trouble with model init

### ISSUE THREAD

**Issue by Sotatek-DuyHoang** [LeslieZhoa/HeadSwap#13]
I run code in colab and when I executed this code
"model = Infer('pretrained_models/epoch_00190_iteration_000400000_checkpoint.pt',
            'pretrained_models/Blender-401-00012900.pth',
            'pretrained_models/parsing.pth',
            'pretrained_models/epoch_20.pth',
            'pretrained_models/BFM')"
            
There appeared an error below
"            ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-18-e632070f31a7>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model = Infer('pretrained_models/epoch_00190_iteration_000400000_checkpoint.pt',
      2             'pretrained_models/Blender-401-00012900.pth',
      3             'pretrained_models/parsing.pth',
      4             'pretrained_models/epoch_20.pth',
      5             'pretrained_models/BFM')

2 frames
[/usr/lib/python3.10/enum.py](https://localhost:8080/#) in __getattr__(cls, name)
    435             return cls._member_map_[name]
    436         except KeyError:
--> 437             raise AttributeError(name) from None
    438 
    439     def __getitem__(cls, name):

AttributeError: _3D"

Please help me fix it

**Comment by LeslieZhoa** [comment]
Bug is fixed, please pull and try again!
